management.server.address=127.0.0.1
management.server.port=8098
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}
