package com.example.EnterpriseRagCommunity.service.ai;

public enum LlmQueueTaskType {
    CHAT,
    MULTIMODAL_CHAT,
    TEXT_CHAT,
    IMAGE_CHAT,
    MODERATION,
    MULTIMODAL_MODERATION,
    TEXT_MODERATION,
    IMAGE_MODERATION,
    MODERATION_CHUNK,
    TITLE_GEN,
    TOPIC_TAG_GEN,
    LANGUAGE_TAG_GEN,
    SUMMARY_GEN,
    TRANSLATION,
    EMBEDDING,
    POST_EMBEDDING,
    SIMILARITY_EMBEDDING,
    RERANK,
    UNKNOWN
}
