ALTER TABLE totp_secrets
    ADD COLUMN algorithm VARCHAR(16) NOT NULL DEFAULT 'SHA1' COMMENT 'HMAC 算法（SHA1/SHA256/SHA512）' AFTER secret_encrypted,
    ADD COLUMN digits TINYINT UNSIGNED NOT NULL DEFAULT 6 COMMENT '验证码位数（6/8）' AFTER algorithm,
    ADD COLUMN period_seconds SMALLINT UNSIGNED NOT NULL DEFAULT 30 COMMENT '时间步长（秒）' AFTER digits,
    ADD COLUMN skew TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '允许时间偏移窗口（步数）' AFTER period_seconds;

