ALTER TABLE users
    MODIFY COLUMN status ENUM('ACTIVE','DISABLED','PENDING','EMAIL_UNVERIFIED','DELETED') NOT NULL DEFAULT 'ACTIVE' COMMENT '账户状态';

UPDATE users
SET status = 'EMAIL_UNVERIFIED'
WHERE status = 'PENDING';

ALTER TABLE users
    MODIFY COLUMN status ENUM('ACTIVE','DISABLED','EMAIL_UNVERIFIED','DELETED') NOT NULL DEFAULT 'ACTIVE' COMMENT '账户状态';

