-- Supported languages for translate preferences and admin config
-- MySQL 8.0, InnoDB, utf8mb4

CREATE TABLE supported_languages (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
  language_code VARCHAR(32) NOT NULL COMMENT '语言代码（BCP-47 / ISO）',
  display_name VARCHAR(128) NOT NULL COMMENT '显示名称（UI 展示）',
  native_name VARCHAR(128) NULL COMMENT '本地语言名称（可选）',
  is_active TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序顺序',
  UNIQUE KEY uk_supported_languages_code (language_code),
  KEY idx_supported_languages_active_sort (is_active, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='支持语言表';

INSERT INTO supported_languages (language_code, display_name, native_name, is_active, sort_order) VALUES
('en', '英语（English）', 'English', 1, 1),
('zh-CN', '简体中文（Simplified Chinese）', '简体中文', 1, 2),
('zh-TW', '繁体中文（Traditional Chinese）', '繁體中文', 1, 3),
('fr', '法语（French）', 'Français', 1, 4),
('es', '西班牙语（Spanish）', 'Español', 1, 5),
('ar', '阿拉伯语（Arabic）', 'العربية', 1, 6),
('ru', '俄语（Russian）', 'Русский', 1, 7),
('pt', '葡萄牙语（Portuguese）', 'Português', 1, 8),
('de', '德语（German）', 'Deutsch', 1, 9),
('it', '意大利语（Italian）', 'Italiano', 1, 10),
('nl', '荷兰语（Dutch）', 'Nederlands', 1, 11),
('da', '丹麦语（Danish）', 'Dansk', 1, 12),
('ga', '爱尔兰语（Irish）', 'Gaeilge', 1, 13),
('cy', '威尔士语（Welsh）', 'Cymraeg', 1, 14),
('fi', '芬兰语（Finnish）', 'Suomi', 1, 15),
('is', '冰岛语（Icelandic）', 'Íslenska', 1, 16),
('sv', '瑞典语（Swedish）', 'Svenska', 1, 17),
('nn', '新挪威语（Norwegian Nynorsk）', 'Norsk nynorsk', 1, 18),
('nb', '书面挪威语（Norwegian Bokmål）', 'Norsk bokmål', 1, 19),
('ja', '日语（Japanese）', '日本語', 1, 20),
('ko', '朝鲜语/韩语（Korean）', '한국어', 1, 21),
('vi', '越南语（Vietnamese）', 'Tiếng Việt', 1, 22),
('th', '泰语（Thai）', 'ไทย', 1, 23),
('id', '印度尼西亚语（Indonesian）', 'Bahasa Indonesia', 1, 24),
('ms', '马来语（Malay）', 'Bahasa Melayu', 1, 25),
('my', '缅甸语（Burmese）', 'မြန်မာဘာသာ', 1, 26),
('tl', '他加禄语（Tagalog）', 'Tagalog', 1, 27),
('km', '高棉语（Khmer）', 'ខ្មែរ', 1, 28),
('lo', '老挝语（Lao）', 'ລາວ', 1, 29),
('hi', '印地语（Hindi）', 'हिन्दी', 1, 30),
('bn', '孟加拉语（Bengali）', 'বাংলা', 1, 31),
('ur', '乌尔都语（Urdu）', 'اردو', 1, 32),
('ne', '尼泊尔语（Nepali）', 'नेपाली', 1, 33),
('he', '希伯来语（Hebrew）', 'עברית', 1, 34),
('tr', '土耳其语（Turkish）', 'Türkçe', 1, 35),
('fa', '波斯语（Persian）', 'فارسی', 1, 36),
('pl', '波兰语（Polish）', 'Polski', 1, 37),
('uk', '乌克兰语（Ukrainian）', 'Українська', 1, 38),
('cs', '捷克语（Czech）', 'Čeština', 1, 39),
('ro', '罗马尼亚语（Romanian）', 'Română', 1, 40),
('bg', '保加利亚语（Bulgarian）', 'Български', 1, 41),
('sk', '斯洛伐克语（Slovak）', 'Slovenčina', 1, 42),
('hu', '匈牙利语（Hungarian）', 'Magyar', 1, 43),
('sl', '斯洛文尼亚语（Slovenian）', 'Slovenščina', 1, 44),
('lv', '拉脱维亚语（Latvian）', 'Latviešu', 1, 45),
('et', '爱沙尼亚语（Estonian）', 'Eesti', 1, 46),
('lt', '立陶宛语（Lithuanian）', 'Lietuvių', 1, 47),
('be', '白俄罗斯语（Belarusian）', 'Беларуская', 1, 48),
('el', '希腊语（Greek）', 'Ελληνικά', 1, 49),
('hr', '克罗地亚语（Croatian）', 'Hrvatski', 1, 50),
('mk', '马其顿语（Macedonian）', 'Македонски', 1, 51),
('mt', '马耳他语（Maltese）', 'Malti', 1, 52),
('sr', '塞尔维亚语（Serbian）', 'Српски', 1, 53),
('bs', '波斯尼亚语（Bosnian）', 'Bosanski', 1, 54),
('ka', '格鲁吉亚语（Georgian）', 'ქართული', 1, 55),
('hy', '亚美尼亚语（Armenian）', 'Հայերեն', 1, 56),
('azj', '北阿塞拜疆语（North Azerbaijani）', 'Azərbaycanca', 1, 57),
('kk', '哈萨克语（Kazakh）', 'Қазақша', 1, 58),
('uzn', '北乌兹别克语（Northern Uzbek）', 'Oʻzbekcha', 1, 59),
('tg', '塔吉克语（Tajik）', 'Тоҷикӣ', 1, 60),
('sw', '斯瓦西里语（Swahili）', 'Kiswahili', 1, 61),
('af', '南非语（Afrikaans）', 'Afrikaans', 1, 62),
('yue', '粤语（Cantonese）', '粵語', 1, 63),
('lb', '卢森堡语（Luxembourgish）', 'Lëtzebuergesch', 1, 64),
('li', '林堡语（Limburgish）', 'Limburgs', 1, 65),
('ca', '加泰罗尼亚语（Catalan）', 'Català', 1, 66),
('gl', '加利西亚语（Galician）', 'Galego', 1, 67),
('ast', '阿斯图里亚斯语（Asturian）', 'Asturianu', 1, 68),
('eu', '巴斯克语（Basque）', 'Euskara', 1, 69),
('oc', '奥克语（Occitan）', 'Occitan', 1, 70),
('vec', '威尼斯语（Venetian）', 'Vèneto', 1, 71),
('sc', '撒丁语（Sardinian）', 'Sardu', 1, 72),
('scn', '西西里语（Sicilian）', 'Sicilianu', 1, 73),
('fur', '弗留利语（Friulian）', 'Furlan', 1, 74),
('lmo', '隆巴底语（Lombard）', 'Lombard', 1, 75),
('lij', '利古里亚语（Ligurian）', 'Ligure', 1, 76),
('fo', '法罗语（Faroese）', 'Føroyskt', 1, 77),
('als', '托斯克阿尔巴尼亚语（Tosk Albanian）', 'Shqip', 1, 78),
('szl', '西里西亚语（Silesian）', 'Ślōnskŏ gŏdka', 1, 79),
('ba', '巴什基尔语（Bashkir）', 'Башҡорт', 1, 80),
('tt', '鞑靼语（Tatar）', 'Татар', 1, 81),
('acm', '美索不达米亚阿拉伯语（Mesopotamian Arabic）', 'العربية', 1, 82),
('ars', '内志阿拉伯语（Najdi Arabic）', 'العربية', 1, 83),
('arz', '埃及阿拉伯语（Egyptian Arabic）', 'العربية', 1, 84),
('apc', '黎凡特阿拉伯语（Levantine Arabic）', 'العربية', 1, 85),
('acq', '闪米特阿拉伯语（Ta''izzi-Adeni Arabic）', 'العربية', 1, 86),
('prs', '达里语（Dari）', 'دری', 1, 87),
('aeb', '突尼斯阿拉伯语（Tunisian Arabic）', 'العربية', 1, 88),
('ary', '摩洛哥阿拉伯语（Moroccan Arabic）', 'العربية', 1, 89),
('kea', '克里奥尔语（Kabuverdianu）', 'Kabuverdianu', 1, 90),
('tpi', '托克皮辛语（Tok Pisin）', 'Tok Pisin', 1, 91),
('ydd', '意第绪（Eastern Yiddish）', 'ייִדיש', 1, 92),
('sd', '信德阿拉伯语（Sindhi）', 'سنڌي', 1, 93),
('si', '僧伽罗语（Sinhala）', 'සිංහල', 1, 94),
('te', '泰卢固语（Telugu）', 'తెలుగు', 1, 95),
('pa', '旁遮普语（Punjabi）', 'ਪੰਜਾਬੀ', 1, 96),
('ta', '泰米尔语（Tamil）', 'தமிழ்', 1, 97),
('gu', '古吉拉特语（Gujarati）', 'ગુજરાતી', 1, 98),
('ml', '马拉雅拉姆语（Malayalam）', 'മലയാളം', 1, 99),
('mr', '马拉地语（Marathi）', 'मराठी', 1, 100),
('kn', '卡纳达语（Kannada）', 'ಕನ್ನಡ', 1, 101),
('mag', '马加拉语（Magahi）', 'मगही', 1, 102),
('or', '奥里亚语（Oriya）', 'ଓଡ଼ିଆ', 1, 103),
('awa', '阿瓦德语（Awadhi）', 'अवधी', 1, 104),
('mai', '迈蒂利语（Maithili）', 'मैथिली', 1, 105),
('as', '阿萨姆语（Assamese）', 'অসমীয়া', 1, 106),
('hne', '切蒂斯格尔语（Chhattisgarhi）', 'छत्तीसगढ़ी', 1, 107),
('bho', '比哈尔语（Bhojpuri）', 'भोजपुरी', 1, 108),
('min', '米南加保语（Minangkabau）', 'Minangkabau', 1, 109),
('ban', '巴厘语（Balinese）', 'Basa Bali', 1, 110),
('jv', '爪哇语（Javanese）', 'Basa Jawa', 1, 111),
('bjn', '班章语（Banjar）', 'Banjar', 1, 112),
('su', '巽他语（Sundanese）', 'Basa Sunda', 1, 113),
('ceb', '宿务语（Cebuano）', 'Cebuano', 1, 114),
('pag', '邦阿西楠语（Pangasinan）', 'Pangasinan', 1, 115),
('ilo', '伊洛卡诺语（Iloko）', 'Ilokano', 1, 116),
('war', '瓦莱语（Waray (Philippines)）', 'Winaray', 1, 117),
('ht', '海地语（Haitian）', 'Kreyòl ayisyen', 1, 118),
('pap', '帕皮阿门托语（Papiamento）', 'Papiamentu', 1, 119);

